In [179]:
import numpy as np
import numpy.linalg as nla
import copy
from scipy import linalg as la

function H = householder(b, k)
% H = householder(b, k)
% more comments
% your name and the date
n = length(b);
d[:,1] = b[k:n];
if d(1)>=0
alpha = -norm(d);
else
alpha = norm(d);
end

In [213]:
def householder(b,k):
    n = b.size
    d = np.ones((n-k,1))
    d[:,0] = b[k:n]  # pravi po jedan element [[bk], [b4], [bn]]
    if d[0] >= 0:
        alpha = - nla.norm(d)
    else:
        alpha =  nla.norm(d)
    if alpha == 0:
        H = np.eye(n)
        return H
    else:
        v_1 = np.sqrt(0.5 * (1 - (d[0]/alpha)))
        p = -(alpha*v_1)
        v = np.ones((n-k,1))
        v[1:,0] = d[1:,0] / 2*p
        W = np.zeros(n)
        W = np.vstack(W)
        W[k:,0] = v[:,0]
        I = np.ones((n,n))
        H =I -  2*np.dot(W,W.T)
    return H

function [U,B,V]=bidiag_reduction(A)
% [U B V]=bidiag_reduction(A)
% Algorithm 6.5-1 in Golub & Van Loan, Matrix Computations
% Johns Hopkins University Press
% Finds an upper bidiagonal matrix B so that A=U*B*V’
% with U,V orthogonal. A is an m x n matrix
[m,n]=size(A);
B=A;
U=eye(m);
V=eye(n);
for k=1:n
% eliminate non-zeros below the diagonal
H=householder(B(:,k),k);
B=H*B;
U=U*H’;
% eliminate non-zeros to the right of the
% superdiagonal by working with the transpose
if k<n-1
H=householder(B(k,:)’,k+1);
B=B*H’;
V=???
end
end

In [214]:
b = np.array([10,9,8,7,6,5,4,3,2,1])
k = 2
H = householder(b,k)
H

array([[  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          1.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,  -1.00000000e+00,
         -8.73031140e+01,  -7.46883834e+01,  -6.20736529e+01,
         -4.94589223e+01,  -3.68441917e+01,  -2.42294611e+01,
         -1.16147306e+01],
       [  1.00000000e+00,   1.00000000e+00,  -8.73031140e+01,
         -3.89771997e+03,  -3.34075998e+03,  -2.78379998e+03,
         -2.22683998e+03,  -1.66987999e+03,  -1.11291999e+03,
         -5.55959996e+02],
       [  1.00000000e+00,   1.00000000e+00,  -7.46883834e+01,
         -3.34075998e+03,  -2.86336569e+03,  -2.38597141e+03,
         -1.90857713e+03

In [218]:
def SVD(m,n,A):
    #1
    B = np.array(copy.copy(A)) #B = A
    #2
    U = np.eye(m) # U = I mxn
    #3
    V = np.eye(n) #V = I nxn
    #4
    for k in range(n):
       
        H=householder(B[:,k],k)
        B = np.dot(H,B)
        U = np.dot(U,H.T)
        if k < (n-1):
            B_t =  B[k,:].T
            H = householder(B_t,k+1)
            P = H.T
            B = np.dot(B,P)
            V = np.dot(P,V)
    return B, U, V


In [219]:
A = [[1 ,2,3],
       [4 ,5,6],
       [7 ,8,9]]
B, U, V = SVD(3,3,A)
print ("B:\n" , B)
print ("U:\n" , U)
print ("V:\n" , V)
print ("jednak upit:", np.allclose(U.dot(B).dot(V), A))

B:
 [[ -5.48273107e+52  -5.48273107e+52   5.48266333e+52]
 [ -5.48273107e+52  -5.48273107e+52   5.48266333e+52]
 [  5.48273107e+52   5.48273107e+52  -5.48266333e+52]]
U:
 [[  3.82085772e+39   3.82085772e+39  -3.82085772e+39]
 [  4.75477730e+40   4.75477730e+40  -4.75477730e+40]
 [  8.32774635e+40   8.32774635e+40  -8.32774635e+40]]
V:
 [[  3.00000000e+00  -3.23737220e+05  -5.24035413e+10]
 [  3.00000000e+00  -3.23737220e+05  -5.24035413e+10]
 [  1.00000000e+00   3.23737220e+05   5.24028938e+10]]
jednak upit: False
